spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SickGu
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

logging:
  level:
    root: debug